/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as ProtectedWorkflowsRouteImport } from './routes/_protected/workflows'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as Protected404RouteImport } from './routes/_protected/404'
import { Route as ProtectedWorkflowWorkflowIdRouteImport } from './routes/_protected/workflow.$workflowId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkflowsRoute = ProtectedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const Protected404Route = Protected404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWorkflowWorkflowIdRoute =
  ProtectedWorkflowWorkflowIdRouteImport.update({
    id: '/workflow/$workflowId',
    path: '/workflow/$workflowId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof Protected404Route
  '/dashboard': typeof ProtectedDashboardRoute
  '/workflows': typeof ProtectedWorkflowsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/workflow/$workflowId': typeof ProtectedWorkflowWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof Protected404Route
  '/dashboard': typeof ProtectedDashboardRoute
  '/workflows': typeof ProtectedWorkflowsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/workflow/$workflowId': typeof ProtectedWorkflowWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/404': typeof Protected404Route
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/workflows': typeof ProtectedWorkflowsRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_protected/workflow/$workflowId': typeof ProtectedWorkflowWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/dashboard'
    | '/workflows'
    | '/auth/signin'
    | '/auth/signup'
    | '/workflow/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/dashboard'
    | '/workflows'
    | '/auth/signin'
    | '/auth/signup'
    | '/workflow/$workflowId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/404'
    | '/_protected/dashboard'
    | '/_protected/workflows'
    | '/auth/signin'
    | '/auth/signup'
    | '/_protected/workflow/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/workflows': {
      id: '/_protected/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof ProtectedWorkflowsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/404': {
      id: '/_protected/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Protected404RouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/workflow/$workflowId': {
      id: '/_protected/workflow/$workflowId'
      path: '/workflow/$workflowId'
      fullPath: '/workflow/$workflowId'
      preLoaderRoute: typeof ProtectedWorkflowWorkflowIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  Protected404Route: typeof Protected404Route
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedWorkflowsRoute: typeof ProtectedWorkflowsRoute
  ProtectedWorkflowWorkflowIdRoute: typeof ProtectedWorkflowWorkflowIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  Protected404Route: Protected404Route,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedWorkflowsRoute: ProtectedWorkflowsRoute,
  ProtectedWorkflowWorkflowIdRoute: ProtectedWorkflowWorkflowIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
